### ISSUE TITLE
Timestamps shouldn't rely on current frame

### ISSUE THREAD

**Issue by Speykious** [vignetteapp/MediaPipe.NET#15]
This way of creating timestamps is actually wrong.
We should actually use the current time in microseconds, like we did in Akihabara.
https://github.com/vignetteapp/MediaPipe.NET/blob/73cd0429f8e1d75644ca5d63db8974a7a9b08928/Mediapipe.Net/Calculators/CpuCalculator.cs#L29

**Comment by sr229** [comment]
I consider this a regression if we're doing something backwards from Akihabara, so you might need to either port that back in or rewrite in a manner that preserves that previous behavior.

**Comment by sr229** [comment]
Things had changed on 0.9.1 so I don't think this is relevant anymore.
