### ISSUE TITLE
Let `ImageFrame` take pixel data as a `ReadOnlySpan<byte>` instead of a `byte*`

### ISSUE THREAD

**Issue by Speykious** [vignetteapp/MediaPipe.NET#16]
This will improve the API by making it possible to disallow unsafe blocks for high level examples.
While we want to use `unsafe` in place of any kind of marshaling as much as possible internally, externally we would want to *hide* it as much as possible (by default, that is).
Related constructor: https://github.com/vignetteapp/MediaPipe.NET/blob/73cd0429f8e1d75644ca5d63db8974a7a9b08928/Mediapipe.Net/Framework/Format/ImageFrame.cs#L34-L50

**Comment by RishiKumarRay** [comment]
unsafe public ImageFrame(ImageFormat format, int width, int height, int widthStep, ReadOnlySpan<byte>* pixelData)
is it right ? @Speykious can i raise a PR if this is right?

**Comment by Speykious** [comment]
> unsafe public ImageFrame(ImageFormat format, int width, int height, int widthStep, ReadOnlySpan* pixelData) is it right ? @Speykious can i raise a PR if this is right?

It isn't right, though you can still raise a PR as all I would need to do is to request changes. :)
It would rather be
```cs
unsafe public ImageFrame(ImageFormat format, int width, int height, int widthStep, ReadOnlySpan<byte> pixelData)
```

**Comment by RishiKumarRay** [comment]
@Speykious please review

**Comment by sr229** [comment]
Just so we're clear we still need to cast these Spans into bytes, yes?

**Comment by Speykious** [comment]
Yes, it's just a matter of providing a nice abstraction to the unsafe constructor.
