### ISSUE TITLE
BlazePoseCpuCalculator crashing

### ISSUE THREAD

**Issue by johnye2e** [vignetteapp/MediaPipe.NET#21]
I've tried using the code from Mediapipe.Net.Examples.FaceMesh with BlazePoseCpuCalculator (after adding necessary medipipe / graphs and modules folder) on Windows 10, and I get the following exception 
![image](https://user-images.githubusercontent.com/9825174/154548019-fc0035b7-acb7-42fd-84fa-8025e960b7a4.png)

Where can I find a working example for this calculator?

**Comment by johnye2e** [comment]
@Speykious do you have a working example for BlazePoseCpuCalculator?

**Comment by Speykious** [comment]
As I said, the example you just tried is supposed to be working, so effectively we don't have a fully working one.

**Comment by Speykious** [comment]
We made the examples synchronous and also fixed a critical memory leak. Maybe you could try again now?

**Comment by johnye2e** [comment]
The issue is not fixed.

**Comment by johnye2e** [comment]
Yes, I use discord. What's the server?

**Comment by Speykious** [comment]
[Here it is.](https://discord.gg/Tz96ZdKjSA)

Welcome :)

**Comment by sr229** [comment]
From what I can repro, I think we're sending something and MP *is* returning something, but it's not getting it.

**Comment by Speykious** [comment]
The exact bug:
- if we allow the calculator to return empty frames, then as more images are added to the input stream, an internal error occurs.
```cs
        protected override ImageFrame SendFrame(ImageFrame frame)
        {
            using ImageFramePacket packet = new ImageFramePacket(frame, new Timestamp(CurrentFrame));
            Graph.AddPacketToInputStream(INPUT_VIDEO_STREAM, packet).AssertOk();

            ImageFramePacket outPacket = new ImageFramePacket();
            System.Console.WriteLine($"Queue size: {framePoller.QueueSize}");
            if (framePoller.Next(outPacket))
                return outPacket.Get();
            else
                return frame;
        }
```
![image](https://user-images.githubusercontent.com/13885008/155290426-1b245749-ca7d-4bed-8c27-f523241c4081.png)
- on the other hand, if we trap `framePoller.Next(outPacket)` inside of a while loop, it gets completely stuck.
```cs
        protected override ImageFrame SendFrame(ImageFrame frame)
        {
            using ImageFramePacket packet = new ImageFramePacket(frame, new Timestamp(CurrentFrame));
            Graph.AddPacketToInputStream(INPUT_VIDEO_STREAM, packet).AssertOk();

            ImageFramePacket outPacket = new ImageFramePacket();
            System.Console.WriteLine($"Queue size: {framePoller.QueueSize}");
            while (!framePoller.Next(outPacket))
                Thread.Sleep(1);

            return outPacket.Get();
        }
```
![image](https://user-images.githubusercontent.com/13885008/155291421-0bfec131-e1ad-4485-a7cf-4afcb60d483d.png)
