### ISSUE TITLE
how to work opencvsharp together?

### ISSUE THREAD

**Issue by interiv** [vignetteapp/MediaPipe.NET#32]
how to work opencvsharp together?
mat type is not  support
videocapture read  a pic from camera.
how  to use it?

**Comment by adryzz** [comment]
are you trying to use this along with OpenCVSharp to read an image from the camera?

**Comment by interiv** [comment]
yes
i see this is use seeshark, but Even if you use seeshark, it is still very inconvenient

**Comment by Speykious** [comment]
Hello, indeed the `Mat` type is not supported. To allow any library to interact with MediaPipe.NET, we directly take a span of bytes.
See https://github.com/vignetteapp/MediaPipe.NET/blob/0388ceaa40685e2e76abfbea99f80d378013cb43/Mediapipe.Net.Examples.FaceMesh/Program.cs#L84-L87

**Comment by sr229** [comment]
> how to work opencvsharp together? mat type is not support videocapture read a pic from camera. how to use it?

Hello, MediaPipe.NET comes with it's own OpenCV too, making it incompatible with OpenCVSharp if it doesn't matches the CV version of MP.

**Comment by interiv** [comment]
> Hello, indeed the `Mat` type is not supported. To allow any library to interact with MediaPipe.NET, we directly take a span of bytes. See
> 
> https://github.com/vignetteapp/MediaPipe.NET/blob/0388ceaa40685e2e76abfbea99f80d378013cb43/Mediapipe.Net.Examples.FaceMesh/Program.cs#L84-L87

I'll try

**Comment by interiv** [comment]
> Hello, indeed the `Mat` type is not supported. To allow any library to interact with MediaPipe.NET, we directly take a span of bytes. See
> 
> https://github.com/vignetteapp/MediaPipe.NET/blob/0388ceaa40685e2e76abfbea99f80d378013cb43/Mediapipe.Net.Examples.FaceMesh/Program.cs#L84-L87

cFrame is seeshark frame,not mat type

**Comment by interiv** [comment]
> > how to work opencvsharp together? mat type is not support videocapture read a pic from camera. how to use it?
> 
> Hello, MediaPipe.NET comes with it's own OpenCV too, making it incompatible with OpenCVSharp if it doesn't matches the CV version of MP.

how to use it's own opencv?

**Comment by sr229** [comment]
> > Hello, indeed the `Mat` type is not supported. To allow any library to interact with MediaPipe.NET, we directly take a span of bytes. See
> > https://github.com/vignetteapp/MediaPipe.NET/blob/0388ceaa40685e2e76abfbea99f80d378013cb43/Mediapipe.Net.Examples.FaceMesh/Program.cs#L84-L87
> 
> cFrame is seeshark frame,not mat type

Please read again, we take `Span<byte>`. Please convert your `Mat` to `Span<byte>`.

**Comment by Speykious** [comment]
ok
