### ISSUE TITLE
Getting this error - System.IO.DirectoryNotFoundException: 'Could not find a part of the path '/mediapipe/graphs/face_mesh/face_mesh_desktop_live.pbtxt

### ISSUE THREAD

**Issue by amalcty** [vignetteapp/MediaPipe.NET#36]
System.IO.DirectoryNotFoundException: 'Could not find a part of the path '/mediapipe/graphs/face_mesh/face_mesh_desktop_live.pbtxt

I'm getting this error when I try to initialize the facemeshcpucalculator in a MAUI project.

**Comment by sr229** [comment]
Please provide actionable logs and code samples so we can work with your issue better.

**Comment by Speykious** [comment]
Remember that Mediapipe resources such as graphs and modules are not provided by MediaPipe.NET.
You can find them in the [original mediapipe repo](https://github.com/google/mediapipe) under `mediapipe/graphs` and `mediapipe/modules`.

In particular, the graph you're looking for is [here](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_mesh/face_mesh_desktop_live.pbtxt).

**Comment by Speykious** [comment]
It also needs to be under the same directory structure, with the `mediapipe/` folder directly visible to the executable.
However, you can also create a child of the [`ResourceManager`](https://github.com/vignetteapp/MediaPipe.NET/blob/master/Mediapipe.Net/Util/ResourceManager.cs) class where you can load resources manually by providing 2 delegate functions.

**Comment by amalcty** [comment]
I have added the mediapipe/ folder directly but still getting the same error. Here is the detailed log

FATAL UNHANDLED EXCEPTION: System.IO.DirectoryNotFoundException: Could not find a part of the path '/mediapipe/graphs/face_mesh/face_mesh_desktop_live_gpu.pbtxt'.
[mono-rt]    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
[mono-rt]    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
[mono-rt]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
[mono-rt]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[mono-rt]    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[mono-rt]    at System.IO.Strategies.UnixFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[mono-rt]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[mono-rt]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
[mono-rt]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
[mono-rt]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[mono-rt]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
[mono-rt]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
[mono-rt]    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
[mono-rt]    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
[mono-rt]    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
[mono-rt]    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
[mono-rt]    at System.IO.File.ReadAllText(String path)
[mono-rt]    at Mediapipe.Net.Calculators.Calculator`2[[Mediapipe.Net.Framework.Packet.NormalizedLandmarkListVectorPacket, Mediapipe.Net, Version=0.8.10.0, Culture=neutral, PublicKeyToken=null],[System.Collections.Generic.List`1[[Mediapipe.Net.Framework.Protobuf.NormalizedLandmarkList, Mediapipe.Net.Framework.Protobuf, Version=0.8.9.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(String graphPath, String secondaryOutputStream)
[mono-rt]    at Mediapipe.Net.Calculators.GpuCalculator`2[[Mediapipe.Net.Framework.Packet.NormalizedLandmarkListVectorPacket, Mediapipe.Net, Version=0.8.10.0, Culture=neutral, PublicKeyToken=null],[System.Collections.Generic.List`1[[Mediapipe.Net.Framework.Protobuf.NormalizedLandmarkList, Mediapipe.Net.Framework.Protobuf, Version=0.8.9.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(String graphPath, String secondaryOutputStream)
[mono-rt]    at Mediapipe.Net.Calculators.FaceMeshGpuCalculator..ctor()
[mono-rt]    at MauiApp1.MainPage.TakePhoto() in C:\Users\amal.b\source\repos\MauiApp1\MauiApp1\MainPage.xaml.cs:line 56
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22

**Comment by Speykious** [comment]
Could you tell me how you run your project and where you placed the `mediapipe/` folder?

**Comment by amalcty** [comment]
I run the project on Android emulator and have placed the mediapipe folder in the MauiApp root folder

**Comment by Speykious** [comment]
You have to place it in the folder where the executable is. I assume it's somewhere in `bin/Debug/[...]/`.

**Comment by Speykious** [comment]
> Android

I'd also like to mention that we never tested MediaPipe.NET on Android before. Our main targets are Windows and Linux. Maybe the Linux shared library isn't adapted for Android, but in that case it's surprising that it didn't crash in the first place...

**Comment by amalcty** [comment]
I tried placing it in this folder bin/Debug/[...]/ or bin/Release/[...] but still getting the same result. 
Could you please give a sample of loading it with resource manager ?

**Comment by Speykious** [comment]
You can look at the [FaceMesh example](https://github.com/vignetteapp/MediaPipe.NET/tree/master/Mediapipe.Net.Examples.FaceMesh). It provides a `DummyResourceManager` and uses it if you run the example with the `--use-resource-manager` option. You could copy the class and extend it with some print statements to see what's going on, it would also help us in the process.
