### ISSUE TITLE
`ResourceManager` delegates are not safe from garbage collection

### ISSUE THREAD

**Issue by Speykious** [vignetteapp/MediaPipe.NET#37]
When creating a child of the `ResourceManager` class, it will execute `SafeNativeMethods.mp__SetCustomGlobalPathResolver__P(ResolvePath);`, which is actually syntactic sugar for `SafeNativeMethods.mp__SetCustomGlobalPathResolver__P(new PathResolver(ResolvePath));`.
The same is true for `SafeNativeMethods.mp__SetCustomGlobalResourceProvider__P(provideResource);`, which is syntactic sugar for `SafeNativeMethods.mp__SetCustomGlobalResourceProvider__P(new UnsafeResourceManager(provideResource));`.

As C# doesn't care at all about the native side, this newly instantiated delegate may be garbage collected at any time during the program, and it will cause an error similar to this:
```
Process terminated. A callback was made on a garbage collected delegate of type 'Mediapipe.Net!Mediapipe.Net.Native.SafeNativeMethods+UnsafeResourceProvider::Invoke'.
```

We need to keep these delegates alive to avoid these problems.
This will be a good opportunity to refactor the `ResourceManager` class into a static solution, because the current singleton way really isn't the best.

**Comment by sr229** [comment]
Worth investigating if we can use GC.KeepAlive for those.
