### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by dbruning** [vignetteapp/MediaPipe.NET#4]
Hi & thanks for your work on this project!
I'm trying to understand what this project actually does. I understand that it has evolved from Akihabara, and that you don't have a readme in place yet, but I'm looking at options to implement blazepose in my WPF application and this looks like one of them.

Once this project is a little further along, can you tell me what you expect the runtime dependencies to be? Does it need Python and GCC to run? Or just to build? Where does it run the machine learning models - tflite? Is Windows even a supported target?

My other option is to re-implement what https://github.com/tensorflow/tfjs-models is doing, in pose-detection/src/blazepose_tfjs/detector.ts - which I think is kind of a custom implementation of the "glue" parts of mediapipe, using tensorflow to actually run the models.  But if I'm making that effort, I might be better to instead contribute to this project.

Thanks for any guidance.

**Comment by adryzz** [comment]
> Does it need Python and GCC to run? Or just to build?
No, we already built the native runtime library [here](https://github.com/vignetteapp/MediaPipe.NET.Runtime) ([NuGet](https://www.nuget.org/packages/Mediapipe.Net.Runtime.CPU/)).

> Where does it run the machine learning models - tflite

The models are [here](https://github.com/google/mediapipe/tree/master/mediapipe/modules), and you should be able to load them from a managed byte array if i'm not mistaken. (`System.IO.File.ReadAllBytes()`)

> Is Windows even a supported target?

Yes! Although it is currently experimental as listed [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) (you do not need to follow that  installation guide)

Our "main" build target is Windows too.

As for custom tensorflow, it is a mess, and can't reccommend it. Personally never had any experience with raw tensorflow but it is definitely a mess.

**Comment by dbruning** [comment]
Wow that was quick! Thanks for the detailed reply.
I understand that it's CPU-only & experimental on windows.
So just to be clear, with the runtime you've created, I don't need my target machine to have msys2 or bazel or any special build tools? I just reference the MediaPipe.NET.Runtime nuget package, and then the only additional files I need to deploy are the mediapipe models and the .tflite models that they refer to? If so, that's EPIC.

**Comment by adryzz** [comment]
> I don't need my target machine to have msys2 or bazel or any special build tools

Unless you want to build them yourself (e.g. maybe you want them with debug symboles) you do not have to do any of that.

>  the only additional files I need to deploy are the mediapipe models and the .tflite models that they refer to?

Previously the nodels were at a static path defined by mediapipe itself (e.g. `<current-dir>/mediapipe/modules/...`), now i think we got around that with supplying byte arrays but don't quote me on that one (yet).

We previously also had issues with our packaging, which the "rewrite" should have addressed, so yes you should need only the runtime packages when we're done (e.g. [this](https://www.nuget.org/packages/Mediapipe.Net.Framework.Protobuf/), [this](https://www.nuget.org/packages/Mediapipe.Net.Runtime.CPU/) and additionally [this](https://www.nuget.org/packages/Mediapipe.Net.Runtime.GPU/) for GPU on supported platforms.)

**Comment by dbruning** [comment]
OK, great. Is there anything I can do to help that will also speed me towards being able to run BlazePose with this library?

**Comment by adryzz** [comment]
We manage development on [our discord server](https://discord.gg/Tz96ZdKjSA) (there's a dedicated channel for this project), so if you want to have a closer look at the development/help out you'll find us there.

**Comment by Speykious** [comment]
Yup, we have to add a Readme basically.
I just remembered that we also have to port examples from Akihabara now that the framework has been fully ported. I'll put that under a new issue as well and keep this one for the Readme.

**Comment by sr229** [comment]
Putting this on my TODO.

**Comment by Speykious** [comment]
This readme looks alright

**Comment by sr229** [comment]
Got lazy but I think the README should be fine now xd

**Comment by Speykious** [comment]
@dbruning So just a quick update: there is now a readme on the repository alog with 3 different examples that you can take a look at. Enjoy :)
