### ISSUE TITLE
Are there plans to support ARM64? Windows 11 on ARM64

### ISSUE THREAD

**Issue by joesdu** [vignetteapp/MediaPipe.NET#40]
Are there plans to support ARM64? Windows 11 on ARM64

**Comment by sr229** [comment]
There are no immediate plans for ARM64 support due to lack of hardware to test it against.

**Comment by GreenShadeZhang** [comment]
I think it's a good idea

**Comment by joesdu** [comment]
> There are no immediate plans for ARM64 support due to lack of hardware to test it against.

Indeed, Windows Arm Dev Kit is available now: https://blogs.windows.com/windowsdeveloper/2022/10/24/available-today-windows-dev-kit-2023-aka-project-volterra/

And as mentioned by others, Azure now has Ampere Altra Arm VMs: https://azure.microsoft.com/blog/azure-virtual-machines-with-ampere-altra-arm-based-processors-generally-available/

**Comment by sr229** [comment]
> Indeed, Windows Arm Dev Kit is available now: https://blogs.windows.com/windowsdeveloper/2022/10/24/available-today-windows-dev-kit-2023-aka-project-volterra/

We are aware but we do lack the necessary resources to properly test this, we would be glad if someone is willing to sponsor us some kits that we can use so we could get that running but for now we are focusing where we have the resources to do.
