### ISSUE TITLE
how to use local image from facemesh?

### ISSUE THREAD

**Issue by lk97703** [vignetteapp/MediaPipe.NET#41]
i want to us local image ,like this E:\aaaa\6_1\66666.jpg,
but  Mediapipe.Net.Framework.Format.ImageFrame Unable to load local image ，
What should I do?

Thank you!

**Comment by sr229** [comment]
Please provide a sample test case so we can verify if this is a bug.

**Comment by lk97703** [comment]
抱歉，我英语描述不太准确，请允许我用中文描述。
我使用的是官方提供Demo，因为Demo使用SeeShark从摄像头获取帧图像，从而调用new FaceMeshCpuSolution().Compute()。
我在Demo中未找到加载本地图片的方法，所以想咨询下加载本地图片进行识别该怎么做。


非常谢谢！

**Comment by GreenShadeZhang** [comment]
> 抱歉，我英语描述不太准确，请允许我用中文描述。 我使用的是官方提供Demo，因为Demo使用SeeShark从摄像头获取帧图像，从而调用new FaceMeshCpuSolution().Compute()。 我在Demo中未找到加载本地图片的方法，所以想咨询下加载本地图片进行识别该怎么做。
> 
> 非常谢谢！

你可以将图片读取到内存，然后转成那个字节数组传到参数里面。

**Comment by lk97703** [comment]
> 

非常感谢！
