### ISSUE TITLE
Questions about graphPath path settings

### ISSUE THREAD

**Issue by GreenShadeZhang** [vignetteapp/MediaPipe.NET#42]
I encountered a problem MediaPipe.Net using the Windows App SDK application framework, the program will find the mediapipe directory from the path of System C:WindowsSystem32 by default, so I want to set it in the form of a custom directory, I don't know if this function can be opened.
![image](https://user-images.githubusercontent.com/24240675/205065568-854ac0b9-d370-4553-a17e-6bfebd067d4a.png)

**Comment by sr229** [comment]
Looks like this seems to be a problem on your part, please see the osu!framework example to see what's the expected behavior would be. It should seek from the process working directory first.

**Comment by GreenShadeZhang** [comment]
> Looks like this seems to be a problem on your part, please see the osu!framework example to see what's the expected behavior would be. It should seek from the process working directory first.

Okay, I'll try again

**Comment by GreenShadeZhang** [comment]
I found a workaround because the MSIX packager has a limitation on directories, which requires a virtual directory for file copying.

![image](https://user-images.githubusercontent.com/24240675/206336574-fe66a773-0876-4cd6-9abc-5fbb5e6178c2.png)

docs

https://learn.microsoft.com/en-us/windows/msix/desktop/flexible-virtualization#default-msix-behavior
