### ISSUE TITLE
Adding hair segmentation

### ISSUE THREAD

**Issue by mrsaleh** [vignetteapp/MediaPipe.NET#47]
Hi
Do you have the plan to add this feature to the library?
I wanted to add hair segmentation to the library.
how I can do that? and what I need to consider.
Thanks for the amazing work.

**Comment by sr229** [comment]
Heya, at the moment in the 0.9.1 branch, this should be supported given we share the same codebase as MediaPipeUnity by @homuler but I haven't written tests and fix the examples yet, which is a bigger fish to deal with first before validating adding it.
