### ISSUE TITLE
The type or namespace name 'Solutions' does not exist in the namespace 'Mediapipe.Net' 

### ISSUE THREAD

**Issue by kknsy** [vignetteapp/MediaPipe.NET#49]
![image](https://user-images.githubusercontent.com/26211860/221763218-c6413f74-df02-4834-9b0e-94ffcbfe90a0.png)
Excuse me, how to solve this error, thank you

**Comment by sr229** [comment]
Mediapipe.Net.Solutions no longer exists as of 0.9.1-mpu-0.9.1 as there are no proper maintainers for that API surface. Please consider using the raw MediaPipe API provided in the managed layer.

**Comment by zhou123aw** [comment]
@kknsy Hi, guys !
Do you have any update about this issue ?
