### ISSUE TITLE
Properly separate CPU and GPU tests

### ISSUE THREAD

**Issue by Speykious** [vignetteapp/MediaPipe.NET#5]
Due to how the libraries are being used (one package reference for CPU and another for GPU, both incompatible with each other), the way we currently have to switch between CPU and GPU when performing test is by switching the corresponding package reference in `Mediapipe.Net.Tests.csproj`.
https://github.com/vignetteapp/MediaPipe.NET/blob/0eaa7242701ff16261934d9c8ccc95abe8cb5e57/Mediapipe.Net.Tests/Mediapipe.Net.Tests.csproj#L13-L14

This is not good for CI but also for the `.csproj` file as it's not good practice to constantly change the package references.
We have to find a better way to handle the different tests and packages.

Maybe by putting all `GpuOnly` tests into a different project called `Mediapipe.Net.Tests.GPU`?

**Comment by sr229** [comment]
Prefer a different namespace for this and add attributes that skips specific tests from running.

**Comment by Speykious** [comment]
Do you mean different namespace in the same project? Because the idea would be to have one project per runtime.

**Comment by sr229** [comment]
> Do you mean different namespace in the same project? Because the idea would be to have one project per runtime package.

Yes.

**Comment by Speykious** [comment]
Do you have an idea for how we can manage this package reference conflict inside of the same project?

**Comment by sr229** [comment]
Looks like we do have test filters in place now so we can just call this closed.
