### ISSUE TITLE
Alternate solution of Mediapipe.Net.Solutions

### ISSUE THREAD

**Issue by maketo97** [vignetteapp/MediaPipe.NET#51]
Mediapipe.Net.Solutions no longer exists as of 0.9.1-mpu-0.9.1 as there are no proper maintainers for that API surface. Please consider using the raw MediaPipe API provided in the managed layer.

_Originally posted by @sr229 in https://github.com/vignetteapp/MediaPipe.NET/issues/49#issuecomment-1447609928_
         
Could you elaborate more on the solution suggested (using the raw MediaPipe API provided in the managed layer)?

**Comment by sr229** [comment]
See [MediaPipeUnity](https://github.com/homuler/MediaPipeUnity) on their examples. I'm working on porting those when I have the time.
