### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by ivanjimenez** [vignetteapp/MediaPipe.NET#53]
Hi,

I am just trying to build a simple example project such us FaceMesh. I don't know if I have to do any configuration before build. 

I have errors about packets. Should I install an specific version of a packet from nugget.

Any help about run a simple project should be helpful.

Thanks.

![image](https://user-images.githubusercontent.com/908544/231525933-91bc8407-30a6-4842-8fbb-c31eb57e232d.png)

**Comment by sr229** [comment]
The examples have not been updated yet, I don't have the time at the moment to port them all, so please refer to our upstream MediaPipeUnity for examples.

**Comment by ivanjimenez** [comment]
> The examples have not been updated yet, I don't have the time at the moment to port them all, so please refer to our upstream MediaPipeUnity for examples.

It's ok. By now it is not necessary for me to port all code. I just only want a simple project for a WPF/C# application, not Unity. Could you give me any hints to run a simple project with minimal code, please?

Cheers!

**Comment by GeorgeS2019** [comment]
@sr229   Do you have plan to update the dynamics dll?  The original source from Unity has not been updated for a while

**Comment by sr229** [comment]
> @sr229 Do you have plan to update the dynamics dll? The original source from Unity has not been updated for a while

That is something I don't plan to do at the moment, if you're willing to port everything over to the new MediaPipe, our native repository is a good start.

**Comment by GeorgeS2019** [comment]
@sr229 
It is not trivial, 

First, mediapipe_api needs to be updated
https://github.com/homuler/MediaPipeUnityPlugin/tree/master/mediapipe_api

Second, then only it makes sense to update the Native c# codes HERE to match with that

The mediapipe_api has not been updated for 2 months

**Comment by GeorgeS2019** [comment]
The alternative approach is to see if it is possible to still use this project, after you have migrated the samples and use the new features in mediapipe through tlite.

**Comment by sr229** [comment]
Keep in mind we are a downstream project, and we usually just sync from MPU. I will not provide further support beyond that.

**Comment by GeorgeS2019** [comment]
@sr229  I understand, I am pushing MPU to update :-) 

FYI: SeeShark is great, make it work for godot, streaming webcam to Texture2D, just need more working examples from MediaPipe.NET beyond Hello example :-)

**Comment by sr229** [comment]
This should be fixed by now, if there's any issues please let me know.
